# Generated by Django 5.0.2 on 2024-02-24 05:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="account",
            options={
                "ordering": ["family_group", "user", "type", "name"],
                "verbose_name": "Cuenta",
                "verbose_name_plural": "Cuentas",
            },
        ),
        migrations.AlterModelOptions(
            name="accounttype",
            options={
                "ordering": ["name"],
                "verbose_name": "Tipo de Cuenta",
                "verbose_name_plural": "Tipos de Cuenta",
            },
        ),
        migrations.AlterModelOptions(
            name="currency",
            options={
                "ordering": ["code"],
                "verbose_name": "Moneda",
                "verbose_name_plural": "Monedas",
            },
        ),
        migrations.AlterModelOptions(
            name="transaction",
            options={
                "ordering": ["category", "-date", "account"],
                "verbose_name": "Transacción",
                "verbose_name_plural": "Transacciones",
            },
        ),
        migrations.AlterModelOptions(
            name="transactioncategory",
            options={
                "ordering": ["family_group", "user", "name"],
                "verbose_name": "Categoría de Transacción",
                "verbose_name_plural": "Categorías de Transacción",
            },
        ),
    ]
