# Generated by Django 5.0.2 on 2024-02-25 05:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0003_usertrasactioncategory_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transactioncategory",
            name="type",
            field=models.CharField(
                choices=[("IN", "Ingreso"), ("EX", "Egreso"), ("BO", "Ambas")],
                default="BO",
                max_length=2,
                verbose_name="Tipo",
            ),
        ),
        migrations.AlterField(
            model_name="accounttype",
            name="icon",
            field=models.CharField(
                default="fa-solid fa-wallet",
                max_length=80,
                verbose_name="Icono (BootstrapIcon)",
            ),
        ),
        migrations.AlterField(
            model_name="transactioncategory",
            name="icon",
            field=models.CharField(
                default="fa-solid fa-wallet",
                max_length=80,
                verbose_name="Icono (BootstrapIcon)",
            ),
        ),
        migrations.AlterField(
            model_name="transactioncategory",
            name="path",
            field=models.TextField(
                blank=True, editable=False, null=True, verbose_name="Path"
            ),
        ),
    ]
