# Generated by Django 5.0.2 on 2024-02-25 05:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0004_transactioncategory_type_alter_accounttype_icon_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="usertrasactioncategory",
            constraint=models.UniqueConstraint(
                condition=models.Q(("_deleted", False)),
                fields=("user", "category"),
                name="user_category_unique_user_category",
            ),
        ),
    ]
